import produce from 'immer'

let data = [
  {
    "id": "guan1_ka3_1",
    "parentId": "guan1_ka3_1",
    "type": "group",
    "key": "guan1_ka3_1",
    "title": "关卡1"
  },
  {
    "parentId": "guan1_ka3_1",
    "id": "tu2_ceng2_15",
    "key": "tu2_ceng2_15",
    "title": "图层15",
    "type": "layer",
    "visible": true,
    "opacity": 1,
    "blendingMode": "normal",
    "name": "图层15",
    "left": 497,
    "right": 587,
    "top": 2650,
    "bottom": 2741,
    "height": 91,
    "width": 90,
    "mask": {},
    "image": {}
  },
  {
    "parentId": "guan1_ka3_1",
    "id": "tu2_ceng2_14",
    "key": "tu2_ceng2_14",
    "title": "图层14",
    "type": "layer",
    "visible": true,
    "opacity": 1,
    "blendingMode": "normal",
    "name": "图层14",
    "left": 131,
    "right": 223,
    "top": 2514,
    "bottom": 2606,
    "height": 92,
    "width": 92,
    "mask": {},
    "image": {}
  },
  {
    "parentId": "guan1_ka3_1",
    "id": "tu2_ceng2_13",
    "key": "tu2_ceng2_13",
    "title": "图层13",
    "type": "layer",
    "visible": true,
    "opacity": 1,
    "blendingMode": "normal",
    "name": "图层13",
    "left": 309,
    "right": 402,
    "top": 2372,
    "bottom": 2461,
    "height": 89,
    "width": 93,
    "mask": {},
    "image": {}
  },
  {
    "parentId": "guan1_ka3_1",
    "id": "tu2_ceng2_12",
    "key": "tu2_ceng2_12",
    "title": "图层12",
    "type": "layer",
    "visible": true,
    "opacity": 1,
    "blendingMode": "normal",
    "name": "图层12",
    "left": 489,
    "right": 581,
    "top": 2145,
    "bottom": 2237,
    "height": 92,
    "width": 92,
    "mask": {},
    "image": {}
  },
  {
    "parentId": "guan1_ka3_1",
    "id": "tu2_ceng2_11",
    "key": "tu2_ceng2_11",
    "title": "图层11",
    "type": "layer",
    "visible": true,
    "opacity": 1,
    "blendingMode": "normal",
    "name": "图层11",
    "left": 117,
    "right": 210,
    "top": 2051,
    "bottom": 2140,
    "height": 89,
    "width": 93,
    "mask": {},
    "image": {}
  },
  {
    "parentId": "guan1_ka3_1",
    "id": "tu2_ceng2_10",
    "key": "tu2_ceng2_10",
    "title": "图层10",
    "type": "layer",
    "visible": true,
    "opacity": 1,
    "blendingMode": "normal",
    "name": "图层10",
    "left": 309,
    "right": 401,
    "top": 1891,
    "bottom": 1983,
    "height": 92,
    "width": 92,
    "mask": {},
    "image": {}
  },
  {
    "parentId": "guan1_ka3_1",
    "id": "tu2_ceng2_9",
    "key": "tu2_ceng2_9",
    "title": "图层9",
    "type": "layer",
    "visible": true,
    "opacity": 1,
    "blendingMode": "normal",
    "name": "图层9",
    "left": 573,
    "right": 666,
    "top": 1720,
    "bottom": 1809,
    "height": 89,
    "width": 93,
    "mask": {},
    "image": {}
  },
  {
    "parentId": "guan1_ka3_1",
    "id": "tu2_ceng2_8",
    "key": "tu2_ceng2_8",
    "title": "图层8",
    "type": "layer",
    "visible": true,
    "opacity": 1,
    "blendingMode": "normal",
    "name": "图层8",
    "left": 369,
    "right": 461,
    "top": 1641,
    "bottom": 1733,
    "height": 92,
    "width": 92,
    "mask": {},
    "image": {}
  },
  {
    "parentId": "guan1_ka3_1",
    "id": "tu2_ceng2_7",
    "key": "tu2_ceng2_7",
    "title": "图层7",
    "type": "layer",
    "visible": true,
    "opacity": 1,
    "blendingMode": "normal",
    "name": "图层7",
    "left": 131,
    "right": 224,
    "top": 1529,
    "bottom": 1618,
    "height": 89,
    "width": 93,
    "mask": {},
    "image": {}
  },
  {
    "parentId": "guan1_ka3_1",
    "id": "tu2_ceng2_6",
    "key": "tu2_ceng2_6",
    "title": "图层6",
    "type": "layer",
    "visible": true,
    "opacity": 1,
    "blendingMode": "normal",
    "name": "图层6",
    "left": 477,
    "right": 569,
    "top": 1418,
    "bottom": 1510,
    "height": 92,
    "width": 92,
    "mask": {},
    "image": {}
  },
  {
    "parentId": "guan1_ka3_1",
    "id": "tu2_ceng2_5",
    "key": "tu2_ceng2_5",
    "title": "图层5",
    "type": "layer",
    "visible": true,
    "opacity": 1,
    "blendingMode": "normal",
    "name": "图层5",
    "left": 132,
    "right": 225,
    "top": 1300,
    "bottom": 1389,
    "height": 89,
    "width": 93,
    "mask": {},
    "image": {}
  },
  {
    "parentId": "guan1_ka3_1",
    "id": "tu2_ceng2_4",
    "key": "tu2_ceng2_4",
    "title": "图层4",
    "type": "layer",
    "visible": true,
    "opacity": 1,
    "blendingMode": "normal",
    "name": "图层4",
    "left": 316,
    "right": 408,
    "top": 1134,
    "bottom": 1226,
    "height": 92,
    "width": 92,
    "mask": {},
    "image": {}
  },
  {
    "parentId": "guan1_ka3_1",
    "id": "tu2_ceng2_3",
    "key": "tu2_ceng2_3",
    "title": "图层3",
    "type": "layer",
    "visible": true,
    "opacity": 1,
    "blendingMode": "normal",
    "name": "图层3",
    "left": 497,
    "right": 590,
    "top": 1001,
    "bottom": 1090,
    "height": 89,
    "width": 93,
    "mask": {},
    "image": {}
  },
  {
    "parentId": "guan1_ka3_1",
    "id": "tu2_ceng2_2",
    "key": "tu2_ceng2_2",
    "title": "图层2",
    "type": "layer",
    "visible": true,
    "opacity": 1,
    "blendingMode": "normal",
    "name": "图层2",
    "left": 136,
    "right": 226,
    "top": 866,
    "bottom": 959,
    "height": 93,
    "width": 90,
    "mask": {},
    "image": {}
  },
  {
    "parentId": "guan1_ka3_1",
    "id": "tu2_ceng2_1",
    "key": "tu2_ceng2_1",
    "title": "图层1",
    "type": "layer",
    "visible": true,
    "opacity": 1,
    "blendingMode": "normal",
    "name": "图层1",
    "left": 349,
    "right": 438,
    "top": 681,
    "bottom": 768,
    "height": 87,
    "width": 89,
    "mask": {},
    "image": {}
  },
  {
    "parentId": "huo2_dong4_gui1_ze2",
    "id": "huo2_dong4_gui1_ze2",
    "key": "huo2_dong4_gui1_ze2",
    "title": "活动规则",
    "type": "layer",
    "visible": true,
    "opacity": 1,
    "blendingMode": "normal",
    "name": "活动规则",
    "left": 0,
    "right": 161,
    "top": 67,
    "bottom": 125,
    "height": 58,
    "width": 161,
    "mask": {},
    "image": {}
  },
  {
    "parentId": "wo3_de_jiang3_pin3",
    "id": "wo3_de_jiang3_pin3",
    "key": "wo3_de_jiang3_pin3",
    "title": "我的奖品",
    "type": "layer",
    "visible": true,
    "opacity": 1,
    "blendingMode": "normal",
    "name": "我的奖品",
    "left": 603,
    "right": 750,
    "top": 64,
    "bottom": 122,
    "height": 58,
    "width": 147,
    "mask": {},
    "image": {}
  },
  {
    "parentId": "shu4_liang2",
    "id": "shu4_liang2",
    "key": "shu4_liang2",
    "title": "数量",
    "type": "layer",
    "visible": true,
    "opacity": 1,
    "blendingMode": "normal",
    "name": "数量",
    "left": 612,
    "right": 642,
    "top": 683,
    "bottom": 704,
    "height": 21,
    "width": 30,
    "mask": {},
    "text": {
      "value": "x2",
      "font": {
        "name": "Muyao-Softbrush",
        "sizes": [
          23.77972
        ],
        "colors": [
          [
            255,
            109,
            80,
            255
          ]
        ],
        "alignment": [
          "center"
        ]
      },
      "left": 0,
      "top": 0,
      "right": 0,
      "bottom": 0,
      "transform": {
        "xx": 1.261579207949541,
        "xy": 0,
        "yx": 0,
        "yy": 1.2615792079495411,
        "tx": 627.5160735743747,
        "ty": 704.6269829657974
      }
    },
    "image": {}
  },
  {
    "parentId": "ru4_guan3_quan4",
    "id": "ru4_guan3_quan4",
    "key": "ru4_guan3_quan4",
    "title": "入馆券",
    "type": "layer",
    "visible": true,
    "opacity": 1,
    "blendingMode": "normal",
    "name": "入馆券",
    "left": 564,
    "right": 697,
    "top": 560,
    "bottom": 677,
    "height": 117,
    "width": 133,
    "mask": {},
    "image": {}
  },
  {
    "parentId": "you3_jiang3_pai2_ming2",
    "id": "you3_jiang3_pai2_ming2",
    "key": "you3_jiang3_pai2_ming2",
    "title": "有奖排名",
    "type": "layer",
    "visible": true,
    "opacity": 1,
    "blendingMode": "normal",
    "name": "有奖排名",
    "left": 571,
    "right": 684,
    "top": 725,
    "bottom": 849,
    "height": 124,
    "width": 113,
    "mask": {},
    "image": {}
  },
  {
    "parentId": "dang4_an4_ku4",
    "id": "dang4_an4_ku4",
    "key": "dang4_an4_ku4",
    "title": "档案库",
    "type": "layer",
    "visible": true,
    "opacity": 1,
    "blendingMode": "normal",
    "name": "档案库",
    "left": 57,
    "right": 169,
    "top": 560,
    "bottom": 676,
    "height": 116,
    "width": 112,
    "mask": {},
    "image": {}
  },
  {
    "parentId": "bgm",
    "id": "bgm",
    "key": "bgm",
    "title": "bgm",
    "type": "layer",
    "visible": true,
    "opacity": 1,
    "blendingMode": "normal",
    "name": "bgm",
    "left": 0,
    "right": 750,
    "top": 0,
    "bottom": 3149,
    "height": 3149,
    "width": 750,
    "mask": {},
    "image": {}
  },
  {
    "parentId": "Backgro",
    "id": "Backgro",
    "key": "Backgro",
    "title": "Backgro",
    "type": "layer",
    "visible": true,
    "opacity": 1,
    "blendingMode": "normal",
    "name": "Backgro",
    "left": 0,
    "right": 750,
    "top": 0,
    "bottom": 3149,
    "height": 3149,
    "width": 750,
    "mask": {},
    "image": {}
  }
]



export function configData(state = data, action) {
  switch (action.type) {
    case 'CONFIG':
      return action.data
    default:
      return state
  }
}

export function baseConfigData(state = data, action) {
  switch (action.type) {
    case 'BASE':
      return action.data
    default:
      return produce(data, draft => draft)
  }
}
